daq:
  useDMA: 'False'
  IdelayStep: '8'
  L1A_A:
    BX: '0x10'
    prescale: '0x0'
  L1A_B:
    BX: '0x100'
    prescale: '0x0'
  L1A_rand:
    log2period: '8'
  L1A_type: A
  L1A_ext: 0xf
  NChips: '1'
  Number_of_events_per_readout: '-1'
  NEvents: '5000'
  NSamples: '5'
  calib:
    BX_l1a: '0x114'
    BX_req: '0x100'
    l1a_notcalib: '0x1'
  # trophy v2 :
  elinks_daq:
    - { name : 'link0', polarity: 1, idcode: 0 }
    - { name : 'link1', polarity: 1, idcode: 1 }
  elinks_trg:
    - { name : 'link0', polarity: 0, idcode: 0 }
    - { name : 'link1', polarity: 1, idcode: 2 }
    - { name : 'link2', polarity: 1, idcode: 3 }
    - { name : 'link3', polarity: 0, idcode: 1 }
  zmqPushPull_port: '8888'
  delayScanData_port: '8889'
  l1a_enables:
    periodic_l1a_A     : '0x0'
    periodic_l1a_B     : '0x0'
    periodic_l1a_C     : '0x0'
    periodic_l1a_D     : '0x0'
    random_l1a         : '0x0'
    external_l1a       : '0x0'
    block_sequencer    : '0x0'
    periodic_ancillary : '0x0'
  l1a_generator_settings: # type can be 'L1A', 'CALIBREQ' or 'DUMP' while 'CALIBL1A' is not handled ; followMode can be DISABLE, A, B, C or D
    - { name : 'A', BX : '0x18',  length : '174',   type : 'L1A',     prescale : '0x0', followMode : 'DISABLE' }
    - { name : 'B', BX : '0x528', length : '174',   type : 'L1A',     prescale : '0x0', followMode : 'DISABLE' }
    - { name : 'C', BX : '0x828', length : '174',   type : 'L1A',     prescale : '0x0', followMode : 'DISABLE' }
    - { name : 'D', BX : '0x300', length : '174',   type : 'L1A',     prescale : '0x0', followMode : 'DISABLE' }
  l1a_settings:
    bx_spacing: '50'           #Minimum bx spcing between random or external triggers i.e. here : 43 BX between 2 consecutive L1A (when reading 1 BX per event)
    external_debounce: '0xf'   #flags to indicate if external L1A should be debounced (generally a fine idea)
    length: '174'              #number of consequitive L1A to send in case of external trigger; don't know yet if it will have any effect on rand L1A gen
    ext_delay: '0x0'           #8-bit delays for each external L1A input
    log_rand_bx_period: '0x0'  #LOG2(random period) (bigger numbers -> slower trigger rate)
  ancillary_settings:
    bx: '0x10'
    prescale: '0x0'
    length: '10'

global:
  data_push_port: '8888'
  hw_type: TB
  outputDirectory: data
  run_type: default
  serverIP: tbtester1
  #run_num: 99999
roc_s0:
 sc:
  DigitalHalf:
    all:
      L1Offset: 10
  GlobalAnalog:
    all:
      Sw_Rf: 1
      Sw_cd: 4
      Delay87: 2
      Delay9: 2
      Delay40: 2
      Delay65: 2
      Gain_conv: 0x4
      #Dacb_vb_conv: 60
  ReferenceVoltage:
    0:
      Vbg_1v: 4
      Inv_vref: 370
      Noinv_vref: 250
      Toa_vref: 112
      Tot_vref: 370
    1:
      Vbg_1v: 4
      Inv_vref: 375
      Noinv_vref: 250
      Toa_vref: 112
      Tot_vref: 370
  Top:
    all:
      BIAS_I_PLL_D: 63
      EN_HIGH_CAPA: 1
      EN_LOCK_CONTROL: 0
      ERROR_LIMIT_SC: 0
      Phase: 14
      En_PhaseShift: 1
  cm:
    0:
      Dacb: 33
      Sign_dac: 0
      Ref_dac_inv: 0
    1:
      Dacb: 33
      Sign_dac: 0
      Ref_dac_inv: 0
    2:
      Dacb: 33
      Sign_dac: 0
      Ref_dac_inv: 0
    3:
      Dacb: 33
      Sign_dac: 0
      Ref_dac_inv: 0
  calib:
    0:
      Dacb: 33
      Sign_dac: 0
      Ref_dac_inv: 0
    1:
      Dacb: 33
      Sign_dac: 0
      Ref_dac_inv: 0
  ch:
    0:
      Dacb: 30
      Sign_dac: 0
      Ref_dac_inv: 11
    1:
      Dacb: 30
      Sign_dac: 0
      Ref_dac_inv: 13
    2:
      Dacb: 30
      Sign_dac: 0
      Ref_dac_inv: 10
    3:
      Dacb: 28
      Sign_dac: 0
      Ref_dac_inv: 15
    4:
      Dacb: 30
      Sign_dac: 0
      Ref_dac_inv: 12
    5:
      Dacb: 29
      Sign_dac: 0
      Ref_dac_inv: 12
    6:
      Dacb: 33
      Sign_dac: 0
      Ref_dac_inv: 10
    7:
      Dacb: 27
      Sign_dac: 0
      Ref_dac_inv: 5
    8:
      Dacb: 28
      Sign_dac: 0
      Ref_dac_inv: 7
    9:
      Dacb: 29
      Sign_dac: 0
      Ref_dac_inv: 11
    10:
      Dacb: 32
      Sign_dac: 0
      Ref_dac_inv: 14
    11:
      Dacb: 28
      Sign_dac: 0
      Ref_dac_inv: 12
    12:
      Dacb: 29
      Sign_dac: 0
      Ref_dac_inv: 9
    13:
      Dacb: 30
      Sign_dac: 0
      Ref_dac_inv: 8
    14:
      Dacb: 28
      Sign_dac: 0
      Ref_dac_inv: 11
    15:
      Dacb: 30
      Sign_dac: 0
      Ref_dac_inv: 14
    16:
      Dacb: 29
      Sign_dac: 0
      Ref_dac_inv: 10
    17:
      Dacb: 27
      Sign_dac: 0
      Ref_dac_inv: 6
    18:
      Dacb: 30
      Sign_dac: 0
      Ref_dac_inv: 9
    19:
      Dacb: 31
      Sign_dac: 0
      Ref_dac_inv: 7
    20:
      Dacb: 30
      Sign_dac: 0
      Ref_dac_inv: 20
    21:
      Dacb: 30
      Sign_dac: 0
      Ref_dac_inv: 12
    22:
      Dacb: 28
      Sign_dac: 0
      Ref_dac_inv: 4
    23:
      Dacb: 31
      Sign_dac: 0
      Ref_dac_inv: 9
    24:
      Dacb: 29
      Sign_dac: 0
      Ref_dac_inv: 8
    25:
      Dacb: 32
      Sign_dac: 0
      Ref_dac_inv: 17
    26:
      Dacb: 27
      Sign_dac: 0
      Ref_dac_inv: 13
    27:
      Dacb: 29
      Sign_dac: 0
      Ref_dac_inv: 7
    28:
      Dacb: 30
      Sign_dac: 0
      Ref_dac_inv: 6
    29:
      Dacb: 29
      Sign_dac: 0
      Ref_dac_inv: 4
    30:
      Dacb: 33
      Sign_dac: 0
      Ref_dac_inv: 7
    31:
      Dacb: 27
      Sign_dac: 0
      Ref_dac_inv: 5
    32:
      Dacb: 30
      Sign_dac: 0
      Ref_dac_inv: 7
    33:
      Dacb: 31
      Sign_dac: 0
      Ref_dac_inv: 14
    34:
      Dacb: 30
      Sign_dac: 0
      Ref_dac_inv: 12
    35:
      Dacb: 28
      Sign_dac: 0
      Ref_dac_inv: 12
    36:
      Dacb: 33
      Sign_dac: 0
      Ref_dac_inv: 7
    37:
      Dacb: 31
      Sign_dac: 0
      Ref_dac_inv: 10
    38:
      Dacb: 28
      Sign_dac: 0
      Ref_dac_inv: 2
    39:
      Dacb: 30
      Sign_dac: 0
      Ref_dac_inv: 11
    40:
      Dacb: 31
      Sign_dac: 0
      Ref_dac_inv: 6
    41:
      Dacb: 28
      Sign_dac: 0
      Ref_dac_inv: 8
    42:
      Dacb: 27
      Sign_dac: 0
      Ref_dac_inv: 2
    43:
      Dacb: 29
      Sign_dac: 0
      Ref_dac_inv: 2
    44:
      Dacb: 28
      Sign_dac: 0
      Ref_dac_inv: 8
    45:
      Dacb: 28
      Sign_dac: 0
      Ref_dac_inv: 0
    46:
      Dacb: 30
      Sign_dac: 0
      Ref_dac_inv: 8
    47:
      Dacb: 30
      Sign_dac: 0
      Ref_dac_inv: 10
    48:
      Dacb: 29
      Sign_dac: 0
      Ref_dac_inv: 7
    49:
      Dacb: 32
      Sign_dac: 0
      Ref_dac_inv: 8
    50:
      Dacb: 29
      Sign_dac: 0
      Ref_dac_inv: 7
    51:
      Dacb: 30
      Sign_dac: 0
      Ref_dac_inv: 4
    52:
      Dacb: 31
      Sign_dac: 0
      Ref_dac_inv: 8
    53:
      Dacb: 30
      Sign_dac: 0
      Ref_dac_inv: 10
    54:
      Dacb: 29
      Sign_dac: 0
      Ref_dac_inv: 5
    55:
      Dacb: 29
      Sign_dac: 0
      Ref_dac_inv: 10
    56:
      Dacb: 31
      Sign_dac: 0
      Ref_dac_inv: 9
    57:
      Dacb: 28
      Sign_dac: 0
      Ref_dac_inv: 10
    58:
      Dacb: 33
      Sign_dac: 0
      Ref_dac_inv: 12
    59:
      Dacb: 29
      Sign_dac: 0
      Ref_dac_inv: 11
    60:
      Dacb: 28
      Sign_dac: 0
      Ref_dac_inv: 12
    61:
      Dacb: 30
      Sign_dac: 0
      Ref_dac_inv: 6
    62:
      Dacb: 31
      Sign_dac: 0
      Ref_dac_inv: 7
    63:
      Dacb: 29
      Sign_dac: 0
      Ref_dac_inv: 3
    64:
      Dacb: 31
      Sign_dac: 0
      Ref_dac_inv: 12
    65:
      Dacb: 30
      Sign_dac: 0
      Ref_dac_inv: 6
    66:
      Dacb: 32
      Sign_dac: 0
      Ref_dac_inv: 9
    67:
      Dacb: 28
      Sign_dac: 0
      Ref_dac_inv: 8
    68:
      Dacb: 30
      Sign_dac: 0
      Ref_dac_inv: 12
    69:
      Dacb: 30
      Sign_dac: 0
      Ref_dac_inv: 9
    70:
      Dacb: 31
      Sign_dac: 0
      Ref_dac_inv: 8
    71:
      Dacb: 29
      Sign_dac: 0
      Ref_dac_inv: 7
  MasterTdc:
    0:
      GLOBAL_LATENCY_TIME: 10
